/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.1.4 card_me.glb --transform
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'
import {editable as e} from '@theatre/r3f'

export function CardMe(props) {
  const { nodes, materials } = useGLTF('/card-me/card_me-transformed.glb')
  return (
    <e.group theatreKey='card me' {...props} dispose={null}>
      <mesh geometry={nodes.card_me.geometry} material={materials['card lifestyle.003']} />
    </e.group>
  )
}

useGLTF.preload('/card-me/card_me-transformed.glb')
