/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.1.4 card_lifestyle.glb --transform
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'
import {editable as e} from '@theatre/r3f'


export function CardLifestyle(props) {
  const { nodes, materials } = useGLTF('/card-lifestyle/card_lifestyle-transformed.glb')
  return (
    <e.group theatreKey="card" {...props} dispose={null}>
      <mesh geometry={nodes.Cube.geometry} material={materials['card lifestyle']} />
     </e.group>
  )
}

useGLTF.preload('/card-lifestyle/card_lifestyle-transformed.glb')
