/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.1.4 scene.gltf --transform
Author: mas198462 (https://sketchfab.com/mas198462)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/ace-of-diamonds-playing-card-7373dd044c5c4b7887caa91b10f0bd15
Title: Ace of Diamonds Playing Card
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'
import {editable as e} from '@theatre/r3f'


export function PlayingCard(props) {
  const { nodes, materials } = useGLTF('/card/scene-transformed.glb');

  return (
    <group {...props} dispose={null}>
        <e.group theatreKey="card" rotation={[-Math.PI / 2, 0, 0]}>
          <mesh geometry={nodes.Object_2.geometry} material={materials['Scene_-_Root']} />
          <mesh geometry={nodes.Object_3.geometry} material={materials['Scene_-_Root']} />
          <mesh geometry={nodes.Object_4.geometry} material={materials['Scene_-_Root']} />
          <mesh geometry={nodes.Object_5.geometry} material={materials['Scene_-_Root']} />
        </e.group>
    </group>
  )
}

useGLTF.preload('/card/scene-transformed.glb')
